package com.argumentation.backendapi.model;

import jakarta.persistence.*;

/**
 * ArgumentEntity
 * ---------------
 * Represents an argument in the database.
 * Each argument is linked to:
 *   - A claim (stored in the "statements" table)
 *   - A source (stored in the "sources" table)
 *
 * Table: arguments
 */
@Entity
@Table(name = "arguments")
public class ArgumentEntity {

    /**
     * Primary key: Unique identifier for each argument.
     * Auto-generated by the database (IDENTITY strategy).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * The claim (statement) that this argument represents.
     * This creates a many-to-one relationship:
     *   - Many arguments can reference the same claim.
     * Mapped via the "claim" column in the arguments table,
     * which is a foreign key to statements.id.
     */
    @ManyToOne
    @JoinColumn(name = "claim") // foreign key to statements.id
    private StatementEntity claim;

    /**
     * The source (e.g., publication, author, etc.) from which this argument originates.
     * Linked using the "source" column that references sources.name.
     * Many arguments can share the same source.
     */
    @ManyToOne
    @JoinColumn(name = "source", referencedColumnName = "name") // foreign key to sources.name
    private SourceEntity source;

    // ────────────────────────────────
    // Getters and Setters
    // ────────────────────────────────

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public StatementEntity getClaim() {
        return claim;
    }

    public void setClaim(StatementEntity claim) {
        this.claim = claim;
    }

    public SourceEntity getSource() {
        return source;
    }

    public void setSource(SourceEntity source) {
        this.source = source;
    }
}
