package com.argumentation.backendapi.model;

import jakarta.persistence.*;

/**
 * TopicEntity
 * ------------
 * Represents a discussion topic (e.g., "Television", "Social Media").
 * Each topic is linked to a *root argument* that introduces
 * the main claim or thesis for that topic.
 *
 * Table: topics
 */
@Entity
@Table(name = "topics")
public class TopicEntity {

    /**
     * Primary key: unique identifier for each topic.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * The name/title of the topic.
     * Example: "Artificial Intelligence", "Climate Change"
     */
    private String name;

    /**
     * Reference to the *root argument* associated with this topic.
     * Many topics could theoretically share arguments, but typically
     * this is a one-to-one conceptual mapping.
     */
    @ManyToOne
    @JoinColumn(name = "argument_id") // foreign key to arguments.id
    private ArgumentEntity argument;

    // ────────────────────────────────
    // Getters and Setters
    // ────────────────────────────────

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ArgumentEntity getArgument() {
        return argument;
    }

    public void setArgument(ArgumentEntity argument) {
        this.argument = argument;
    }
}
